import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BookMarked, FileText, Heart, Loader2, Search, Sparkles, Zap, Quote } from 'lucide-react'
import { supabase } from '../supabase.js'
import Feedback from '../components/Feedback.jsx'

const FALLBACK_COVER = 'https://placehold.co/400x560/111827/94a3b8?text=MIMOUVERSE+MANGA'
const ANIME_QUOTE = { text: 'Plus Ultra !', source: 'My Hero Academia' }

function normalizeManga(row, index) { return { id: row.id || `manga-${index}`, title: row.title || row.name || row.nom || 'Sans titre', author: row.author || row.author_name || row.auteur || 'Auteur inconnu', category: row.category || row.genre || 'Manga', description: row.description || '', cover: row.cover_url || row.cover || row.image_url || row.thumbnail_url || FALLBACK_COVER, file: row.pdf_url || row.file_url || row.pdf || row.file || row.document_url || '' } }

export default function Manga() {
  const [manga, setManga] = useState([]), [query, setQuery] = useState(''), [category, setCategory] = useState('Tous'), [favorites, setFavorites] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState('')
  useEffect(() => { let active = true; const load = async () => { if (!supabase) { setError('Supabase n’est pas configuré.'); setLoading(false); return }; const { data, error: queryError } = await supabase.from('manga').select('*').order('created_at', { ascending: false }); if (!active) return; if (queryError) setError(queryError.message); else setManga((data || []).map(normalizeManga)); setLoading(false) }; load(); return () => { active = false } }, [])
  const categories = useMemo(() => ['Tous', ...Array.from(new Set(manga.map((item) => item.category).filter(Boolean)))], [manga])
  const filtered = useMemo(() => manga.filter((item) => { const text = `${item.title} ${item.author} ${item.category}`.toLowerCase(); return text.includes(query.toLowerCase()) && (category === 'Tous' || item.category === category) }), [manga, query, category])
  const toggleFavorite = (id) => setFavorites((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const openFile = (file) => { if (file) window.open(file, '_blank', 'noopener,noreferrer') }
  return <main className="manga-page">
    <section className="manga-hero"><div className="manga-hero-orb orb-one"/><div className="manga-hero-orb orb-two"/><div className="manga-hero-copy"><div className="manga-eyebrow"><Zap size={14}/> MIMOUVERSE MANGA</div><h1>Entre dans le <span>manga.</span></h1><p>Découvre les mangas réellement publiés sur MIMOUVERSE et ouvre leurs fichiers directement.</p><div className="manga-hero-actions"><span><Sparkles size={15}/> Nouvelles séries au fil des publications</span></div></div><div className="manga-stack" aria-hidden="true"><div className="manga-panel panel-back">M</div><div className="manga-panel panel-mid">V</div><div className="manga-panel panel-front"><BookMarked size={48}/><strong>MANGA</strong><small>MIMOUVERSE</small></div></div></section>
    <section className="manga-content"><div className="manga-quote"><div><span className="quote-label"><Quote size={11}/> Citation anime</span><p className="quote-text">« {ANIME_QUOTE.text} »</p><p className="quote-author">— {ANIME_QUOTE.source}</p></div></div><div className="manga-section-heading"><div><span className="kicker">Explorer</span><h2>Les mangas publiés</h2></div><p>Chaque publication ajoutée par l’administrateur apparaît automatiquement ici.</p></div><div className="manga-tools"><div className="manga-search"><Search size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher une série, un auteur..."/></div><div className="manga-categories">{categories.map((item) => <button key={item} className={category === item ? 'manga-category active' : 'manga-category'} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="manga-section-heading compact"><div><span className="kicker">Catalogue réel</span><h2>À découvrir</h2></div><span className="manga-result">{filtered.length} série{filtered.length > 1 ? 's' : ''}</span></div>
      {loading ? <div className="manga-empty"><Loader2 size={30}/><h3>Chargement des mangas...</h3><p>Connexion au catalogue MIMOUVERSE.</p></div> : error ? <div className="manga-empty"><Search size={28}/><h3>Catalogue temporairement indisponible</h3><p>{error}</p></div> : filtered.length === 0 ? <div className="manga-empty"><Search size={28}/><h3>Aucun manga publié</h3><p>Les nouvelles séries apparaîtront ici dès leur publication.</p></div> : <div className="manga-grid">{filtered.map((item) => <article className="manga-card violet" key={item.id}><div className="manga-cover"><img src={item.cover} alt={`Couverture de ${item.title}`} style={{width:'100%',height:'100%',objectFit:'cover',borderRadius:14}} onError={(e) => { e.currentTarget.src = FALLBACK_COVER }}/><span className="manga-tag">{item.category}</span><button className={favorites.includes(item.id) ? 'manga-favorite selected' : 'manga-favorite'} onClick={() => toggleFavorite(item.id)} aria-label={`Ajouter ${item.title} aux favoris`}><Heart size={18} fill={favorites.includes(item.id) ? 'currentColor' : 'none'}/></button></div><div className="manga-info"><div className="manga-meta-top"><span>{item.author}</span><span>{item.file ? <><FileText size={13}/> Fichier disponible</> : 'Fichier manquant'}</span></div><h3>{item.title}</h3><p>{item.description || 'Une nouvelle œuvre à découvrir dans MIMOUVERSE.'}</p><div className="manga-card-bottom"><span>{item.category}</span><button disabled={!item.file} onClick={() => openFile(item.file)}>{item.file ? <>Ouvrir <ArrowRight size={15}/></> : 'Indisponible'}</button></div></div></article>)}</div>}
    </section>
    <Feedback type="manga" items={manga} />
  </main>
}
